<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>Brezee.App</RootNamespace>
    <AssemblyName>Brezee</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Brezee.Bridge\Brezee.Bridge.vcxproj" />
  </ItemGroup>

</Project>
